name: advedro
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  get_storage: ^2.0.3
  dartz: ^0.10.1
  equatable: ^2.0.3
  dio: ^4.0.6
  cupertino_icons: ^1.0.2
  path_provider: ^2.0.14
  flutter_image_compress: ^1.1.3
  image_picker: ^0.8.8
  permission_handler: ^10.1.0
  video_player: ^2.6.1
  fl_chart: ^0.61.0
  flutter_native_splash: ^2.2.19
  hive: ^2.2.3
  image_cropper: ^3.0.2
  flutter_local_notifications: ^13.0.0
  flutter_easyloading: ^3.0.5
  device_info_plus: ^8.2.2
  intl: ^0.18.1
  google_nav_bar: ^5.0.6
  navbar_router: ^0.5.0
  textfield_tags: ^2.0.2
  animated_button_bar: ^1.0.0
  path: ^1.8.2


dev_dependencies:
  flutter_launcher_icons: ^0.13.0

  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/launcher/logo.png
    - assets/launcher/splash.png

  fonts:
    - family: AssetResource
      fonts:
        - asset: assets/fonts/AssetResource.ttf
    - family: ubuntu_r
      fonts:
        - asset: assets/fonts/ubuntu_r.ttf

flutter_native_splash:
  color: "#ede5f4"
  fullscreen: true
  image: "assets/launcher/splash.png"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/launcher/logo.png"
  min_sdk_android: 21