/// Flutter icons AssetResource
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  AssetResource
///      fonts:
///       - asset: fonts/AssetResource.ttf
///
///
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
///
import 'package:flutter/widgets.dart';

class AssetResource {
  AssetResource._();

  static const _kFontFam = 'AssetResource';
  static const String? _kFontPkg = null;

  static const IconData affiliant = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData barChartAltTwo = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData close = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData edit = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData config = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bottomArrow = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bell = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fingerPrint = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData info = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData play = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trash = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData campaign = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData check = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData circleCheck = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevronDown = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevronRight = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevronUp = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData create = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData editSquare = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData export = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData flow = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heatMap = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hide = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ideaLamp = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData landing = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData layer = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData leftArrow = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData media = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData menu = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData moreVertical = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData offers = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData news = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pause = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plus = IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData powerOff = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rightArrow = IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData showEye = IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData targetLock = IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData traffic = IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData union = IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user = IconData(0xe829, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData upArrow = IconData(0xe82a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData timer = IconData(0xe82b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bxLayer = IconData(0xe82c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData moreHoriz = IconData(0xea1b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData moreVert = IconData(0xea1c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
